= aws-lambda-slack-bot
:toc: left
:sectnums:

AWS Lambdaのカスタムランタイムを管理する場所。

== 依存性

- Nim 1.4.4
- Python3
  - awscli
- direnv

== ビルド方法

リポジトリ直下の config.nims にビルドタスクを定義しています。
これを以下のコマンドで使用します。

[source,source]
----
$ nim buildDist
----

実行すると `dist` ディレクトリ配下に bootstrap.zip とそれ以外にも複数のzipファイ
ルが作成されます。

== AWS Labmda の構成とデプロイの関係

まず、構成として AWS APIGateway と AWS Lambda を使用します。

bootstrap.zip は AWS Lambda のカスタムランタイムレイヤー用のZipファイルです。
AWS Lambda Function を作成する際には、この bootstrap.zip のみ登録したレイヤーを
作成し、Functionには作成したレイヤーを登録するようにします。

次に、それ以外のzipファイルは、いずれもLambda Function用の実行可能ファイルが含ま
れています。

これらはすべてAWS Lambda Function 1つにそれぞれ1つのZipをアップロードする想定で
います。

== デプロイ

現状はデプロイを自動化していないため、ローカルでコマンドを実行する必要があります。
`.envrc` を作成する必要があるので、 `.envrc.example` をコピーします。
コピーしたらエディタで編集して、環境変数を設定します。

[source,source]
----
$ cp .envrc.example .evnrc
$ vim .evnrc
----

設定が完了したら以下のコマンドでデプロイされます。

[source,console]
----
$ nim deployFunction
----

== 認証周り

現状特に認証周りを設けていないのでAPIは叩き放題ですが、
API Gatewayのスロットリング設定でリクエスト数に制限を設けることで叩き放題になら
ないようにある程度保護しています。

いずれ認証の設定を入れます。
